<!DOCTYPE html>
<html lang="<?= $locale ?>" dir="<?= $locale === 'ar' ? 'rtl' : 'ltr' ?>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="application/vnd.wap.xhtml+xml; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes">
    <meta name="HandheldFriendly" content="true">
    <meta name="MobileOptimized" content="width">
    <meta content="yes" name="apple-mobile-web-app-capable">
    <meta name="telegram:channel" content="@uzforuz">
    <meta name="Generator" content="UZFOR.UZ">
    <?= $this->section('meta', '') ?>
    <?php if (! empty($keywords)): ?>
        <meta name="keywords" content="<?= $this->e($keywords) ?>">
    <?php endif ?>
    <?php if (! empty($description)): ?>
        <meta name="description" content="<?= $this->e($description) ?>">
    <?php endif ?>
    <?php if (! empty($canonical)): ?>
        <link rel="canonical" href="<?= $canonical ?>">
    <?php endif ?>
    <link rel="stylesheet" href="<?= $this->asset('css/style.css', true) ?>">
    <link rel="stylesheet" href="<?= $this->asset('css/sidebar.css', true) ?>">
    <meta property="og:site_name" content="UZFOR.UZ">
    <meta name="copyright" content="UZFOR.UZ - 2017">
    <meta name="author" content="Akbarali">
    <meta name="web_content_type" content="Tips">
    <meta name="country" content="UZ">
    <meta name="reply-to" content="akbarali@uzhackersw.uz">
    <meta name="robots" content="index, follow">
    <meta name="resource-type" content="document">
    <meta name="classification" content="internet">
    <meta name="distribution" content="global">
    <meta name="rating" content="safe for kids">
    <meta name="doc-type" content="public">
    <meta name="Identifier-URL" content="<?=$config['homeurl']?>">
    <meta name="contactOrganization" content="UZFOR.UZ - Bizning forum!">
    <meta name="contactZipcode" content="221100">
    <meta name="contactCity" content="Namangan">
    <meta name="contactCountry" content="Uzbekistan">
    <meta name="contactNetworkAddress" content="info@uzhackersw.uz">
    <meta name="linkage" content="<?=$config['homeurl']?>">
    <meta name="dc.source" content="<?=$config['homeurl']?>">
    <meta name="dc.relation" content="<?=$config['homeurl']?>">
    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#537397">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#537397">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-status-bar-style" content="#537397">
    <style>
      .uzfor_progress {
      position: fixed;
      bottom: 0;
      z-index: 1;
      width: 100%;
      background-color: #f1f1f1;
      border-radius: 18px;
      }
      .progress-container {
      width: 100%;
      height: 4px;
      background: #fff;
      }
      .progress-bar {
      height: 4px;
      background: #5d80a6;
      width: 0%;
      border-radius: 2px;
      }
      div.sticky {
      position: -webkit-sticky;
      position: -moz-sticky;
      position: -ms-sticky;
      position: -o-sticky;
      position: sticky;
      top: 0;
      }
    </style>
    <link rel="shortcut icon" href="https://uzfor.uz/images/favicon.ico">
    <title><?= (isset($title) ? $this->e($title) : $config['copyright']) ?></title>
  </head>
  <body class="">
   
    <style>
      .tungi-rejim {
      background-color: #1e1e2e;
      }
      .tungi-rejim .menu, .tungi-rejim .w3-sidebar {
      background: #27293d;
      color: #5d80a6;
      }
      .tungi-rejim .topclassd {
      background: #1e1e2e;
      border: 2px solid #419ef9;
      opacity: 0.8;
      }
      .tungi-rejim a:link, .tungi-rejim a:visited, .tungi-rejim a:active {
      color: #9a9a9a;
      text-decoration: none;
      }
      .tungi-rejim .yashirish {
      display: none;
      }
      .tungi-rejim .phdr, .tungi-rejim .tmn {
      background: #1e1e2e;
      color: #55677d;
      border: 0px;
      }
      .tungi-rejim .tmn img {
      display: none;
      }
      .tungi-rejim .border-bottom {
      border-bottom: 1px solid #1e1e2e!important;
      margin: 0px 10px;
      }
      .tungi-rejim .mfoot {
      border-top: 1px solid #1e1e2e;
      }
      .tungi-rejim textarea {
      background: #1e1e2e;
      border: 1px solid #1e1e2e;
      }
      .tungi-rejim a.mm_item:hover {
      background: #1e1e2e;
      text-decoration: none;
      }
    </style>
    <script>
      function TungiRejim() {
         var element = document.body;
         element.classList.toggle("tungi-rejim");
      }
    </script>
    <button style="position: fixed;left: 0;top:0;padding: 4px;margin: 10px;" class="a" onclick="TungiRejim()">Tungi rejim</button>
    <div style="width: 1100px;margin: auto;max-width: 100%;">

    <?= $this->section('chap-menyu', $this->fetch('system::app/chap-menyu')) ?>

      <div class="w3-main" style="margin-left: 270px;">
        <div class="w3-teal">
          <div class="menu" style="padding: 2px;border-radius: 4px;">
            <div class="topclassd sticky">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tbody>
                  <tr>
                    <td class="w3-hide-large">
                      <a class="topa w3-button w3-teal w3-xlarge w3-hide-large" onclick="w3_open()" style="font-size: 20px;">
                      <img src="https://uzfor.uz/images/uzfor_hamburger.png?v=0.0.1" style="margin-bottom: -3px; height: 18px;" alt="Menu "></a>
                    </td>
                    <td>
                      <a class="topa" href="<?=$config['homeurl']?>">
                      <img src="https://uzfor.uz/images/svg/home.svg" style="margin-bottom: -3px; height: 18px;" alt="Bosh sahifa">
                      </a>
                    </td>
                    <td>
                      <a class="topa" href="<?=$config['homeurl']?>/forum/admin/yangi/">
                        <img src="https://uzfor.uz/images/svg/tasma.svg" style="margin-bottom: -3px; height: 18px;" alt="Lenta "> <!-- 415 -->
                      </a>
                    </td>
                    <td>
                      <a class="topa" href="https://uzfor.uz/chat/index.php">
                      <img src="https://uzfor.uz/images/svg/chat.svg" style="margin-bottom: -4px; height: 20px;" alt="Chat"> 42 
                      </a>
                    </td>
                    <td id="languages">
                      <a class="topa" id="cirilica" style="cursor: pointer;" onclick="$('#cirilica').hide();$('#latinica').fadeIn();$('#latinica').html();" title="Ўзбек кирилл алифбосига ўтиш">
                      O'zb
                      </a>
                      <a class="topa" id="latinica" style="display: none;cursor: pointer;" onclick="$('#latinica').hide();$('#cirilica').fadeIn();$('#cirilica').html();" title="O'zbek lotin alifbosiga o'tish">
                      O'zb
                      </a>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <style>
              .menubar_count {
              border-radius: 9px;
              background: #ff3347;
              font-size: 12px;
              color: #fff;
              padding: 0 4px;
              position: absolute;
              }
            </style>
            <div class="topclassd" style="position: fixed;bottom: 0;box-shadow: 0px 10px 10px 6px #00000045;border-radius: 0;background: rgba(255,255,255,.14);-webkit-backdrop-filter: blur(12px);backdrop-filter: blur(12px);border: 0;width: 1100px;margin: auto;max-width: 100%;left: 0;right: 0;">
              <ul>
                <table width="100%" cellpadding="0" cellspacing="0">
                  <tbody>
                    <tr>
                      <td>
                        <li style="text-align: center;" class="mmi_docs">
                          <a href="<?=$config['homeurl']?>/forum/admin/yangi/" data-skiponclick="1" class="mm_item al_menu" align="center">
                            <i style="float: none;" class="i_icon">
                              <div class="svgIcon svgIcon-menu svgIcon-menu__document_outline_28"></div>
                            </i>
                          </a>
                        </li>
                      </td>
                      <td>
                        <li style="text-align: center;" class="mmi_answers">
                          <a href="/notifications.php" data-skiponclick="1" class="mm_item al_menu">
                            <i style="float: none;" class="i_icon">
                              <div class="svgIcon svgIcon-menu svgIcon-menu__notify"></div>
                            </i>
                          </a>
                        </li>
                      </td>
                      <td>
                        <li style="text-align: center;" class="mmi_mail">
                          <a href="/mail.php" data-skiponclick="1" class="mm_item al_menu">
                            <i style="float: none;" class="i_icon">
                              <div class="svgIcon svgIcon-menu svgIcon-menu__message_outline_28"></div>
                            </i>
                          </a>
                        </li>
                      </td>
                      <td>
                        <li style="text-align: center;" class="mmi_feed">
                          <a href="/pay.php" data-skiponclick="1" class="mm_item al_menu">
                            <i style="float: none;" class="i_icon">
                              <div class="svgIcon svgIcon-menu svgIcon-menu__uzforpay"></div>
                            </i>
                          </a>
                        </li>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </ul>
            </div>
            <?= $this->section('content') ?>
            <div class="tmn">
              <div><a href="https://uzfor.uz/users.php?act=online"><img src="https://uzfor.uz/theme/default/images/menu_online.png" alt="-" class="icon"> Onlayn: 59 (3/56)</a></div>
              <div><a href="https://uzfor.uz/profile.php"><img src="https://uzfor.uz/theme/default/images/menu_cabinet.png" alt="-" class="icon"> Shaxsiy profil</a><br></div>
              <div><a href="https://uzfor.uz/search.php"><img src="https://uzfor.uz/theme/default/images/tool.png" alt="-" class="icon"> Forumdan qidirish</a><br></div>
              <br>
              <div> - Faol mavzular soni: <b> 2,746 ta</b></div>
              <div> - Barcha xabarlar soni:<b> 85,024 ta</b></div>
              <div>- Forum a'zolari: <b>4,749 nafar</b></div>
              <div>- So'ngi a'zo: <b> <a href="/profile.php?user=8977" <b="">BOYBOLA1XBETSTAVKA</a></b></div>
            </div>
            <div class="phdr">
              © 2017-2021 UZFOR.UZ clon <a href="https://t.me/kbarali">Akbarali</a> tomonidan qilingan <br>
              <a href="/qoida.php">Qoidalar</a> *
              <a href="/malumotnoma.php">Ma'lumotnoma</a> *
              <a href="/reklama.php?act=reklama_berish">Reklama</a> *
              <a href="/about.php">Sayt haqida</a> *
              <a href="/sayt_xaritasi.php">Sayt xaritasi</a> *
              <a href="/stat.php">Sayt statistikasi</a>
            </div>
          </div>
          <center>
            Tezlik: 0.195<br>
            <br>
          </center>
        </div>
      </div>
    </div>
  </body>
</html>