<?php
// Подключаем основной шаблон сайта
$this->layout(
  'system::layout/uzfor',
  [
    'title'      => $data['title'], // Передаем заголовок страницы в тег title
    'page_title' => $data['title'], // Передаем заголовок страницы в тег h1
  ]
);

// d($data['forum_cat'])
?>
<div class="maintxt">
  <form name="form" action="?" method="post">
    <div class="phdr"><b>Mavzu ochish</b> | <b>Aforizmlar</b></div>
    <div class="menu">
      Podforum:
      <div class="br"></div>
      <select name="ichki_cat">
        <option >Tanlang</option>
        <?php foreach ($data['forum_cat'] as $item) {  ?>
            <option value="<?=$item->id?>" <?php if (isset($data['fields']['ichki_cat']))  {
                if ($data['fields']['ichki_cat'] == $item->id) {
               echo 'selected';
            }
            }?>><?=$item->name?></option>
        <?php } ?>
      </select>
      <div class="br"></div>
      Kategoriya nomini kiriting:<span style="color: red;">*</span>
      <div class="br"></div>
      <input type="text" size="20" maxlength="100" name="catname" value="">
      <p></p>
      <div class="br"></div>

      <div class="br"></div>
      Kategoriya haqida ozroq tushuncha:<span style="color: red;">*</span>
      <div class="br"></div>
      <textarea rows="3" name="msg"></textarea>
      <p></p>
      <p><input type="submit" value="Kategoriyani yaratish" style="cursor: pointer;"> 
    </div>
  </form>
  <div class="menu"><span style="color: red;">*</span> - To'ldirish majburiy bo'lgan maydonlar</div>
</div>