<?php
  // Подключаем основной шаблон сайта
  $this->layout(
    'system::layout/uzfor',
    [
      'title'      => $data['title'], // Передаем заголовок страницы в тег title
      'page_title' => $data['title'], // Передаем заголовок страницы в тег h1
    ]
  );
  $forum_theme = $data['forum_theme'];
  $forum_cat = $data['forum_cat'];
  $tashqi_cat = $data['tashqi_cat'];
  $create_user_info = $data['create_user_info'];
  ?>
<style>
  .h2_title_uzfor {
  font-weight: 500;
  font-size: 1.5rem;
  line-height: 1.3;
  text-align: center;
  margin-top: 0px;
  margin-bottom: 10px;
  }
</style>
<div class="maintxt">
  <div class="menu">
    <a href="<?=$config['homeurl']?>"><b><?=$tashqi_cat->name?></b></a> |
    <a href="<?=$config['homeurl']?>forum/<?=$forum_cat->code?>/"><b><?=$forum_cat->name?></b></a> 
  </div>
  <h2 class="h2_title_uzfor"><?=$data['title']?></h2>
  <style>
    .heart {
    cursor: pointer;
    width: 20px;
    height: 30px;
    background: url(/images/svg/like_.svg) no-repeat;
    background-size: contain;
    float: right;
    }
    .heart_active {
    cursor: pointer;
    width: 30px;
    height: 30px;
    background: url(/images/svg/like.svg) no-repeat;
    background-size: 17px;
    float: right;
    text-align: right;
    line-height: 13px;
    color: #ff3347;
    }
    .heart:hover {
    background-image: url(/images/svg/like.svg);
    }
  </style>
  <div class="phdr"><b>Xabarlar</b></div>
  <div class="menu" style="border-bottom: 2px solid #e4e8ed;border-radius: 0;padding-top: 10px;" id="izoh90811">
    <a class="delava" href="/id1">
    <img width="37" height="37" style="float:left;border-radius: 40px;" src="https://uzfor.uz/files/users/photo/87_tmp_1548426402.jpg" alt=""></a>
    <div style="min-height:43px;margin-left:45px;">
      <!-- <img style="width: 18px;vertical-align: -3px;" src="/images/svg/panel.svg"> <img src="/images/group/1.png" width="13" height="13" style="margin-bottom: -2px;" alt="*"> --><b><a href="<?=$config['homeurl']?>/profile/?user=<?=$theme['user_id']?>">Akbarali</a></b> <b>[0]</b> <font color="red">[off]</font>
      <a href="?act=plyus&amp;id=90811&amp;page=1" onclick="LaykBosish()">
        <div class="heart"></div>
      </a>
      <script>
        function LaykBosish() {
          confirm("Ushbu xabarni ijobiy deb baholaysizmi?");
        }
      </script><a href="#">Javob</a> <span style="color: #BFC6CF;">|</span> 
      <a href="#">Sitata</a><br><span><a href="#">#3</a></span> 
      <time><?=$forum_theme->time?></time><br>
    </div>
    <div style="padding-top: 4px;"></div>
    <div>
      <div data-role="commentContent" data-controller="core.front.core.lightboxedImages" style="padding: 0px 0px 10px 0px;"><?=$forum_theme->theme_text?></div>
    </div>
    <div>
      <!--<i><b style="color: #525252;">+ (1):</b> <a href="https://uzfor.uz/@zetpro2003">AkmyradoffSoft</a>, </i>-->
    </div>
  </div>
</div>