<?php
  // Подключаем основной шаблон сайта
  $this->layout(
    'system::layout/uzfor',
    [
      'title'      => $data['title'], // Передаем заголовок страницы в тег title
      'page_title' => $data['title'], // Передаем заголовок страницы в тег h1
    ]
  );

  $forum_cat = $data['forum_cat'];  ?>
<div class="maintxt">
  <form name="form" action="?" method="post">
    <div class="phdr"><b>Mavzu ochish</b> | <b><a href="<?=$config['homeurl']?>/forum/<?=$forum_cat->code?>/"><?=$forum_cat->name?></a></b></div>
    <div class="menu">
      Podforum:
      <div class="br"></div>
      <select disabled="disabled">
        <option><?=$forum_cat->name?></option>
      </select>
      <div class="br"></div>
      Mavzu nomini kiriting:<span style="color: red;">*</span>
      <div class="br"></div>
      <input type="text" size="20" maxlength="100" name="name" value="">
      <p></p>
      <div class="br"></div>
      Mavzuga birinchi postni kiriting:<span style="color: red;">*</span>
      <div class="br"></div>
      <textarea rows="3" name="message"></textarea>
      <p></p>
      <p></p>
      <p><input type="submit" value="Mavzuni ochish" style="cursor: pointer;">
      
      </p>
    </div>
  </form>
  <div class="menu"><span style="color: red;">*</span> - To'ldirish majburiy bo'lgan maydonlar</div>
</div>